export const destinations = [
    {
      title: "Moving Local / Same State",
      content: "Seamless Moves, Within Your State!",
      src: "assets/img/quote/quote-cat-1.jpg",
      srcSet: "assets/img/quote/quote-cat-1.jpg",
      url: "/moving-local",
    },
    {
      title: "Moving Interstate",
      content:
        "Effortless Interstate Moves - Relocate with Ease Across States!",
        src: "assets/img/quote/quote-cat-2.jpg",
        srcSet: "assets/img/quote/quote-cat-2.jpg",
      url: "/moving-inter",
    },
    {
      title: "Moving Office",
      content: "Streamlined Office Moves - Transition Your Workspace with Precision!",
      src: "assets/img/quote/quote-cat-3.jpg",
      srcSet: "assets/img/quote/quote-cat-3.jpg",
      url: "/moving-office",
    },
    {
      title: "Moving Furniture",
      content: "Streamlined Furniture Moves - Transition Your Workspace with Precision!",
      src: "assets/img/quote/quote-cat-11.jpg",
      srcSet: "assets/img/quote/quote-cat-11.jpg",
      url: "/moving-furniture",
    },
    {
      title: "Moving a Single Item",
      content: "Careful Single Item Moves - Precision Handling for Your Valuables!",
      src: "assets/img/quote/quote-cat-4.jpg",
      srcSet: "assets/img/quote/quote-cat-4.jpg",
      url: "/moving-single",
    },
    {
      title: "Moving a few Item",
      content: "Efficient Small Moves - Handling Your Items with Care!",
      src: "assets/img/quote/quote-cat-5.jpg",
      srcSet: "assets/img/quote/quote-cat-5.jpg",
      url: "/moving-more",
    },
    {
      title: "Moving a Piano",
      content: "Expert Piano Moves - Safely Transporting Your Precious Instrument!",
      src: "assets/img/quote/quote-cat-6.jpg",
      srcSet: "assets/img/quote/quote-cat-6.jpg",
      url: "/moving-piano",
    },
    {
      title: "Moving a Pool Table",
      content: "Professional Pool Table Moves - Ensuring Safe and Precise Transport!",
      src: "assets/img/quote/quote-cat-7.jpg",
      srcSet: "assets/img/quote/quote-cat-7.jpg",
      url: "/moving-pool",
    },
    {
      title: "Gumtree/Ebay Pickups",
      content: "Convenient Gumtree/Ebay Pickups - Easy and Reliable Transport!",
      src: "assets/img/quote/quote-cat-8.jpg",
      srcSet: "assets/img/quote/quote-cat-8.jpg",
      url: "/pickups",
    },
    {
      title: "Moving Fragile Items",
      content: "Specialized Fragile Item Moves - Extra Care for Your Delicate Belongings!",
      src: "assets/img/quote/quote-cat-9.jpg",
      srcSet: "assets/img/quote/quote-cat-9.jpg",
      url: "/moving-fragile",
    },
    {
      title: "Rubbish Removal",
      content: "Efficient Rubbish Removal - Clearing Your Space with Ease!",
      src: "assets/img/quote/quote-cat-10.jpg",
      srcSet: "assets/img/quote/quote-cat-10.jpg",
      url: "/rubbish",
    },
  ];
  